### ISSUE TITLE
it would be nice to have very simple examples to show basic usage

### ISSUE THREAD

**Issue by UnixJunkie** [mirage/decompress#25]
The test codes have a different objective (and I already had a look at them).

**Comment by dinosaure** [comment]
A good example is `bin/dpipe.ml` but we have a *cmdliner* noise. I can push a more simplistic example in `bin` (like `zpipe` but without *cmdliner*) if you want.

**Comment by UnixJunkie** [comment]
A super simple example, like a pair of functions: one to compress (the other to decompress) a string
passed as parameter and a compression level would be wonderful.

**Comment by UnixJunkie** [comment]
val compress: int -> string -> t
    val uncompress: t -> string

**Comment by dinosaure** [comment]
It's done by https://github.com/oklm-wsh/Decompress/blob/master/bin/easy.ml but it's just a generic example and I should not to use this in a productive environment.

**Comment by UnixJunkie** [comment]
My god, that's terribly verbose. I'm not sure I want to use this library...

**Comment by dinosaure** [comment]
Yes, it's because it's a low-level API (designed in the same way than `zlib` - and the API of `zlib` has the same problem, like: "oh god, it's too complex to use `zlib`", you can see so many question in Stack Overflow about zlib). We provide the same interface as `camlzip` with `{Deflate,Inflate}.{bytes,bigstring}` and we let the user to control the allocation if they want (like: allocate one `window` for all decompression computes). A good project can be an `ezdecompress` (like `ezirmin` or `ezjsonm`) to provide a more convenient API but it's another job - and I don't want to maintain a high-level API and a low-level API in the same package, I want a light library.

Decompress is designed with lot of constraints about the dependencies (it only depends on `Bigarray`) to work on JavaScript world or MirageOS world for example and because I consider `zlib` as a deep layer of an application (like a web server) and we think about the optimization for the user without any C tricks - and we let the user to do a C trick if they want (and it's what happens in `bin/dpipe.ml` with `bin/bs.c`).

**Comment by dinosaure** [comment]
`decompress` get a stable API now (last change is about performance but it does not change logic behind the API) and I provided a small example to explain how to use `decompress` like:

```ocaml
type inflated = private string

val to_string : inflated -> string
val of_string : string -> inflated
```

With some explanations about memory consumption. I'm able to close this issue now 👍 .
